# Generated by Django 4.1.1 on 2023-05-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(help_text='example@example.com', max_length=200)),
                ('feedback', models.TextField(help_text='Напишіть свій відгук тут...', max_length=1000)),
            ],
        ),
    ]
