# Generated by Django 4.1.1 on 2023-05-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techno_back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Нікнейм артиста', max_length=30)),
                ('index_img', models.CharField(help_text='URL картинки на головній сторінці', max_length=200)),
                ('index_info', models.TextField(help_text='Коротке інфо артиста', max_length=1000)),
                ('carousel1', models.ImageField(help_text='1 картинка артиста', upload_to='carousel-images/')),
                ('carousel2', models.ImageField(blank=True, help_text='2 картинка артиста', null=True, upload_to='carousel-images/')),
                ('carousel3', models.ImageField(blank=True, help_text='3 картинка артиста', null=True, upload_to='carousel-images/')),
                ('bandcamp', models.URLField(help_text='Bandcamp-link')),
                ('instagram', models.URLField(help_text='Instagram-link')),
                ('soundcloud', models.URLField(help_text='Soundcloud-link')),
            ],
        ),
    ]
