# Generated by Django 4.1.1 on 2023-05-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techno_back', '0002_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='full_info',
            field=models.TextField(default='Повна інформація', help_text='Повне інфо артиста', max_length=2000),
        ),
    ]
