# Generated by Django 4.1.1 on 2023-05-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techno_back', '0004_alter_artist_full_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='soundcloud_api',
            field=models.TextField(default='default', help_text='Soundcloud Plugin', max_length=1200),
        ),
    ]
